package com.holymusic.app.core.util

object AppConstants {
    const val khatameQuran: String = "খতমে কুরআন"
    const val directory: String = "/holy_tune/"
    const val mp3: String = ".mp3"
    const val mp4: String = ".mp4"
    const val language: String = "bn"
    const val search: String = "undefined"
    const val typeAudio: String = "A"
    const val typeVideo: String = "V"
    const val gajalArtist: String = "নাশিদ শিল্পী"
    const val gajalAudio: String = "গজল অডিও"
    const val gajalVideo: String = "গজল ভিডিও"
    const val audioAlbum: String = "হলিটিউন প্লেলিস্ট"
    const val videoAlbum: String = "বাছাইকৃত ভিডিও"
    const val audioTraks: String = "জনপ্রিয় গজল"
    const val videoTracks: String = "জনপ্রিয় ভিডিও"
    const val favorite_gajal: String = "ফেভারিট'স গজল"
    const val favorite_gajalVideo: String = "ফেভারিট'স ভিডিও"
    const val audio: String = "অডিও"
    const val video: String = "ভিডিও"
    const val myFavorites: String = "মাই ফেভারিট'স"
    const val downloads: String = "ডাউনলোডস"
    const val deepLinkScreen: String = "screen"
    const val deepLinkId: String = "id"
    const val image: String = "image"
    const val trackType: String = "Track"
    const val shortPlay: String = "ShortPlay"
    const val trending: String = "Trending"
    const val videoScholar: String = "ইসলামিক বক্তা"
    const val local: String = "local"
    const val typeScholarVideo: String = "SV"
    const val typeKhatameQuranVideo: String = "QV"
    const val typeKhatameQuranAudio: String = "QA"
}